---
- hosts: all
  become: true
  become_user: "root"
  tasks:
  - name: make direcotry
    file:
      path: "/home/root/.ssh"
      state: directory
  - name: create empty file
    file:
      path: "/home/root/.ssh/authorized_keys"
      state: touch
  - name: put pubkey
    lineinfile:
      path: "/home/root/.ssh/authorized_keys"
      line: "{{ pubkey }}"
